version: '3'
services:
  assessment:
    container_name: nest-app
    env_file:
      - ./.env.local
    ports:
      - '3000:3000'
      - '3001:3000'
      - '3002:3000'
      - '3003:3000'
    depends_on:
      - db
  db:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '&QyZBeaDY(Xv(xjD'
      POSTGRES_DB: 'owais_db'
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - '8080:80'
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - assessment

volumes:
  postgres-db:
